name: Deploy Services

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy services
      run: |
        ssh -v -o StrictHostKeyChecking=no deployuser@45.95.234.232 << 'EOF'
          export NVM_DIR="\$HOME/.nvm"
          [ -s "\$NVM_DIR/nvm.sh" ] && \. "\$NVM_DIR/nvm.sh"
          export PATH=\$NVM_DIR/versions/node/v18.*/bin:\$PATH
          cd /var/www/swwf
          git reset --hard HEAD
          git clean -fd
          git pull origin master
          npm install
          npm run build-dev
        EOF
