name: Deploy Services

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

    - name: Deploy services
      run: |
        ssh -v -o StrictHostKeyChecking=no root@37.252.23.91 << 'EOF'
          cd /var/www/swwtma
          git reset --hard HEAD
          git clean -fd
          git pull origin master
          npm i
          npm run build-prod
        EOF
